import streamlit as st
import pandas as pd
from datetime import datetime


st.set_page_config(
    page_title="Coach Report",
    page_icon="📄",
    layout="wide"
)

st.title("📄 Coach Report Generator")

st.write(
    """
    This page combines workload-based injury risk and video-based movement risk
    into one coach-style injury prevention report.
    """
)

st.warning(
    "Prototype note: This report is for sports analytics demonstration only and is not a medical diagnosis."
)

st.markdown("---")


def get_risk_level(score):
    if score <= 30:
        return "LOW"
    elif score <= 65:
        return "MEDIUM"
    else:
        return "HIGH"


def generate_report_text(
    athlete_name,
    sport,
    workload_result,
    pose_result,
    combined_score,
    combined_level
):
    report_date = datetime.now().strftime("%Y-%m-%d %H:%M")

    workload_score = workload_result.get("risk_score", "N/A")
    workload_level = workload_result.get("risk_level", "N/A")

    movement_score = pose_result.get("movement_risk_score", "N/A")
    movement_level = pose_result.get("movement_risk_level", "N/A")

    risky_areas = workload_result.get("risky_areas", [])
    workload_reasons = workload_result.get("reasons", [])
    movement_flags = pose_result.get("risk_flags", [])
    average_angles = pose_result.get("average_angles", {})

    report = f"""
ATHLETEBIOMECH AI — COACH INJURY RISK REPORT
Generated: {report_date}

Athlete Name: {athlete_name}
Sport: {sport}

==================================================
FINAL COMBINED RISK
==================================================

Combined Injury Risk Score: {combined_score}%
Combined Risk Level: {combined_level}

Workload Risk Score: {workload_score}%
Workload Risk Level: {workload_level}

Movement Risk Score: {movement_score}%
Movement Risk Level: {movement_level}

==================================================
SPORT-SPECIFIC RISKY BODY AREAS
==================================================
"""

    for area in risky_areas:
        report += f"- {area}\n"

    report += """
==================================================
WORKLOAD RISK REASONS
==================================================
"""

    if workload_reasons:
        for reason in workload_reasons:
            report += f"- {reason}\n"
    else:
        report += "- No major workload risk reasons detected.\n"

    report += """
==================================================
VIDEO MOVEMENT RISK FLAGS
==================================================
"""

    if movement_flags:
        for flag in movement_flags:
            report += f"- {flag}\n"
    else:
        report += "- No major movement risk flags detected.\n"

    report += """
==================================================
AVERAGE JOINT ANGLES
==================================================
"""

    if average_angles:
        for metric, value in average_angles.items():
            report += f"- {metric}: {value} degrees\n"
    else:
        report += "- No joint-angle data available.\n"

    report += """
==================================================
RECOMMENDATIONS
==================================================
"""

    if combined_level == "HIGH":
        report += """- Reduce training load temporarily.
- Increase recovery and rest days.
- Review movement technique with a coach.
- Add mobility, stability, and strengthening exercises.
- Monitor pain, fatigue, or discomfort after sessions.
- Consider physiotherapist review if pain is present.
"""
    elif combined_level == "MEDIUM":
        report += """- Maintain balanced workload and recovery.
- Avoid sudden increase in training volume.
- Add proper warm-up and cooldown.
- Track weekly workload and movement changes.
- Focus on technique correction for flagged movement risks.
"""
    else:
        report += """- Current risk appears manageable.
- Continue tracking workload weekly.
- Maintain strength, mobility, and recovery habits.
- Recheck movement analysis periodically.
"""

    report += """
==================================================
DISCLAIMER
==================================================
This report is generated by an AI sports analytics prototype.
It is intended for educational and performance-analysis purposes only.
It should not be used as a medical diagnosis.
"""

    return report


workload_result = st.session_state.get("workload_result")
pose_result = st.session_state.get("pose_result")
athlete_name = st.session_state.get("athlete_name", "Sample Athlete")
sport = st.session_state.get(
    "selected_sport",
    st.session_state.get("video_sport", "Not Selected")
)


if workload_result is None:
    st.info("Workload risk result not found. Please run the Workload Injury Risk Predictor first.")

if pose_result is None:
    st.info("Video movement result not found. Please run the Video Biomechanics Analyzer first.")


if workload_result is not None and pose_result is not None:
    workload_score = workload_result["risk_score"]
    movement_score = pose_result["movement_risk_score"]

    combined_score = int(round((0.6 * workload_score) + (0.4 * movement_score)))
    combined_level = get_risk_level(combined_score)

    st.subheader(f"Final Report for {athlete_name}")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Combined Injury Risk", f"{combined_score}%")

    with col2:
        st.metric("Final Risk Level", combined_level)

    with col3:
        st.metric("Sport", sport)

    if combined_level == "LOW":
        st.success("LOW Risk: Current workload and movement profile appear manageable.")
    elif combined_level == "MEDIUM":
        st.warning("MEDIUM Risk: Athlete may need workload control and technique improvements.")
    else:
        st.error("HIGH Risk: Athlete has elevated workload and/or movement-related injury risk.")

    st.markdown("---")

    st.markdown("### Risk Score Breakdown")

    score_df = pd.DataFrame({
        "Risk Type": ["Workload Risk", "Movement Risk", "Combined Risk"],
        "Score": [workload_score, movement_score, combined_score]
    })

    st.bar_chart(score_df, x="Risk Type", y="Score")

    st.markdown("---")

    col_a, col_b = st.columns(2)

    with col_a:
        st.markdown("### Workload Risk Reasons")

        for reason in workload_result.get("reasons", []):
            st.write(f"- {reason}")

        st.markdown("### Risky Body Areas")

        for area in workload_result.get("risky_areas", []):
            st.write(f"- {area}")

    with col_b:
        st.markdown("### Video Movement Flags")

        for flag in pose_result.get("risk_flags", []):
            st.write(f"- {flag}")

        st.markdown("### Average Joint Angles")

        angle_df = pd.DataFrame({
            "Metric": list(pose_result.get("average_angles", {}).keys()),
            "Angle": list(pose_result.get("average_angles", {}).values())
        })

        st.dataframe(angle_df, use_container_width=True)

    st.markdown("---")

    st.markdown("### Coach Recommendations")

    if combined_level == "HIGH":
        st.write("- Reduce training load temporarily.")
        st.write("- Increase recovery and rest days.")
        st.write("- Review movement technique with a coach.")
        st.write("- Add mobility, stability, and strengthening exercises.")
        st.write("- Monitor pain, fatigue, or discomfort after sessions.")
    elif combined_level == "MEDIUM":
        st.write("- Maintain balanced workload and recovery.")
        st.write("- Avoid sudden increase in training volume.")
        st.write("- Add proper warm-up and cooldown.")
        st.write("- Focus on technique correction for flagged movement risks.")
    else:
        st.write("- Continue current routine with proper recovery.")
        st.write("- Keep tracking workload weekly.")
        st.write("- Maintain strength and mobility exercises.")

    st.markdown("---")

    report_text = generate_report_text(
        athlete_name=athlete_name,
        sport=sport,
        workload_result=workload_result,
        pose_result=pose_result,
        combined_score=combined_score,
        combined_level=combined_level
    )

    st.markdown("### Download Coach Report")

    st.download_button(
        label="Download Report as TXT",
        data=report_text,
        file_name=f"{athlete_name}_injury_risk_report.txt",
        mime="text/plain"
    )

else:
    st.markdown("---")
    st.write("To generate a complete report, run both:")
    st.write("1. Workload Injury Risk Predictor")
    st.write("2. Video Biomechanics Analyzer")